# Generated by Django 2.2.16 on 2020-10-08 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0002_auto_20201008_0909"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ProoductCategory",
            new_name="ProductCategory",
        ),
    ]
